[package]
name = "kubvernor-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
kubvernor-common.workspace = true
gateway-api.workspace = true
gateway-api-inference-extension.workspace = true
thiserror.workspace = true

[lints]
workspace = true
