[build]
jobs = 4

[http]
timeout = 10                # timeout for each HTTP request, in seconds
low-speed-limit = 1000        # network timeout threshold (bytes/sec)
multiplexing = true         # HTTP/2 multiplexing
