---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-envoy
spec:
  backendtype: envoy
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
spec:
  backendtype: agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-orion
spec:
  backendtype: orion
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-orionproxy-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-orion
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-inference-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
    namespace: gateway-conformance-infra
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
  namespace: gateway-conformance-infra
spec:
  backendtype: agentgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-oriongateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-oriongateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-oriongateway
  namespace: gateway-conformance-infra
spec:
  backendtype: orion
---

