---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-gateway-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-gateway-envoy
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-gateway-orionproxy
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-orionproxy
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-gateway-envoy
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-gateway-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
    namespace: gateway-conformance-infra
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-gateway-orionproxy
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-orionproxy
    namespace: gateway-conformance-infra
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-inference-envoy
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-inference-orionproxy
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-orionproxy
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-conformance-inference-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-envoy
spec:
  backendtype: envoy
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-envoy
  namespace: gateway-conformance-infra
spec:
  backendtype: envoy
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-envoy
  namespace: inference-conformance-infra
spec:
  backendtype: envoy
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
spec:
  backendtype: agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
  namespace: gateway-conformance-infra
spec:
  backendtype: agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
  namespace: inference-conformance-infra
spec:
  backendtype: agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-orionproxy
spec:
  backendtype: orion
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-orionproxy
  namespace: gateway-conformance-infra
spec:
  backendtype: orion
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-orionproxy
  namespace: inference-conformance-infra
spec:
  backendtype: orion
---

