---
apiVersion: v1
kind: Namespace
metadata:
  name: kubvernor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubvernor-control-plane
  namespace: kubvernor
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: kubvernor-control-plane
  template:
    metadata:
      labels:
        app: kubvernor-control-plane
    spec:
      containers:
      - image: kubvernor:main        
        imagePullPolicy: IfNotPresent
        name: kubvernor
        env:
          - name: RUST_LOG
            value: info,kubvernor=info
          - name: RUST_FILE_LOG
            value: info,kubvernor=debug
          - name: RUST_TRACE_LOG
            value: info,kubvernor=debug            
        args:
          - --with-config-file
          - /kubvernor_config/config.yaml   
        ports:
        - name: envoy
          containerPort: 55010
        - name: agentgateway
          containerPort: 55011
        volumeMounts:
          - name: kubvernor-config
            mountPath: /kubvernor_config
            readOnly: true
      serviceAccountName: kubvernor-controller-serviceaccount
      volumes:
        - name: kubvernor-config
          configMap:
            name: kubvernor-config-map
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kubvernor-control-plane
  namespace: kubvernor
spec:
  ports:
    - name: envoy
      port: 55010      
      targetPort: 55010
      protocol: TCP
    - name: agentgateway
      port: 55011
      targetPort: 55011
      protocol: TCP      
  type: ClusterIP
  selector:
    app: kubvernor-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubvernor-controller-role
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - grpcroutes
      - gateways
      - gatewayclasses
      - gatewayclasses/status
    verbs:
      - get
      - watch
      - list
      - patch
      - update
  - apiGroups:
      - inference.networking.k8s.io
    resources:
      - inferencepools
      - inferencepools/status
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - kubvernor.gateway.api
    resources:
      - kubvernorconfigs
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubvernor-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubvernor-controller-role
subjects:
  - namespace: kubvernor
    kind: ServiceAccount
    name: kubvernor-controller-serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubvernor-controller-serviceaccount
  namespace: kubvernor
