---
apiVersion: v1
kind: Namespace
metadata:
  name: kubvernor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubvernor-control-plane
  namespace: kubvernor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubvernor-control-plane
  template:
    metadata:
      labels:
        app: kubvernor-control-plane
    spec:
      containers:
        - image: kubvernor:main
          imagePullPolicy: IfNotPresent
          name: kubvernor
          env:
            - name: RUST_LOG
              value: info,kubvernor=info
            - name: RUST_FILE_LOG
              value: info,kubvernor=debug
            - name: RUST_TRACE_LOG
              value: info,kubvernor=debug
          args:
            - --with-config-file
            - /kubvernor_config/config.yaml
          ports:
            - name: envoy
              containerPort: 50051
            - name: agentgateway
              containerPort: 50052
            - name: orion
              containerPort: 50053
          volumeMounts:
            - name: kubvernor-config
              mountPath: /kubvernor_config
              readOnly: true
      serviceAccountName: kubvernor-controller-serviceaccount
      volumes:
        - name: kubvernor-config
          configMap:
            name: kubvernor-config-map
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kubvernor-control-plane
  namespace: kubvernor
spec:
  ports:
    - name: envoy
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: agentgateway
      port: 50052
      targetPort: 50052
      protocol: TCP
    - name: orion
      port: 50053
      targetPort: 50053
      protocol: TCP
  type: ClusterIP
  selector:
    app: kubvernor-control-plane
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubvernor-config-map
  namespace: kubvernor
data:
  config.yaml: |
    controller_name: kubvernor.com/proxy-controller
    envoy_gateway_control_plane:
      address:
        hostname: kubvernor-control-plane.kubvernor
        port: 50051
    agentgateway_gateway_control_plane:
      address:
        hostname: kubvernor-control-plane.kubvernor
        port: 50052
    orion_gateway_control_plane:
      address:
        hostname: kubvernor-control-plane.kubvernor
        port: 50053

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubvernor-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - namespace: kubvernor
    kind: ServiceAccount
    name: kubvernor-controller-serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubvernor-controller-serviceaccount
  namespace: kubvernor
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-envoy
spec:
  backendtype: envoy
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-agentgateway
spec:
  backendtype: agentgateway
---
apiVersion: kubvernor.gateway.api/v1
kind: KubvernorConfig
metadata:
  name: kubvernor-config-orion
spec:
  backendtype: orion
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-agentgateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-agentgateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-orionproxy-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
  parametersRef:
    group: kubvernor.gateway.api
    kind: KubvernorConfig
    name: kubvernor-config-orion
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubvernor-inference-gateway
spec:
  controllerName: kubvernor.com/proxy-controller
